server:
  port: 3939

  
spring:
  datasource:                                    
    url: jdbc:mysql://111.231.79.149:3306/db_blog?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8
    username: root
    password: Miku@520 
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
      
      
  jpa:
    show-sql: true 
    hibernate: 
      ddl-auto: update   
      
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
           